### ISSUE TITLE
The dragging handlers don't work well when the widget is inside a scroll

### ISSUE THREAD

**Issue by robertohuertasm** [davidanaya/flutter-circular-slider#1]
In our case, the `CircularSlider` is inside a `SingleChildScrollView` and it seems that it gets all the gestures 99% of the times we try to drag.

**Comment by robertohuertasm** [comment]
Just to give you more information, if you grab horizontally the drag handlers it will most probably work. But if you engage in a vertical interaction, the scroll will always win. I don't know if this is easy to fix.

**Comment by davidanaya** [comment]
@robertohuertasm I just uploaded version 1.1.1 could you please try it and let me know if your problem has been solved?
This is the PR that fix the issue https://github.com/davidanaya/flutter-circular-slider/pull/2

**Comment by robertohuertasm** [comment]
It works perfectly! Thanks for this awesome slider!
