### ISSUE TITLE
「onSelectionEnd」 actually holds three parameters, what does each parameter mean?

### ISSUE THREAD

**Issue by fummicc1** [davidanaya/flutter-circular-slider#20]
# Question

Nice to meet you. I am new to Dart and want to make good use of this library.

There is one thing I want to ask.

Although `onSelectionEnd` is commented that its definition takes a function with a parameter of (int init, int end) as an argument, it is actually a function that takes three parameters.

I would like you to teach me the role of each parameter. Thank you.

# My usage

```dart
Center(
  child: SingleCircularSlider(
    12,
    3,
    handlerColor: Colors.black,
    onSelectionEnd: (a, b, c) {
         // I do not figure out what a, b, c parameters mean.
    },
    baseColor: Colors.grey.withOpacity(0.5),
    selectionColor: Colors.deepPurple,
  ),
),
```
<img width="363" alt="スクリーンショット 2019-12-30 15 08 50" src="https://user-images.githubusercontent.com/44002126/71570006-4c717400-2b16-11ea-9353-dc629bd5c68d.png">

**Comment by despie** [comment]
Parameters are defined as follows:
`typedef SelectionChanged<T> = void Function(T a, T b, T c);`

It seems that meaning of parameters are:
a: start of the selection
b: end of the selection
c: loops count

**Comment by fummicc1** [comment]
Thank you!
