### ISSUE TITLE
question

### ISSUE THREAD

**Issue by superciccio** [davidanaya/flutter-circular-slider#3]
in the article you wrote here

https://itnext.io/how-to-build-a-circular-slider-in-flutter-cab3fc5312df

how did you get the line to split the circle ?

is it possible to have only one hadler ( the thing that you drag ) ?

Many thanks

Great work !

**Comment by davidanaya** [comment]
Hi @superciccio 
Not sure I understand your first question.
I'll look into the one handler thing and release a new version.

**Comment by davidanaya** [comment]
@superciccio  new version released, you can use now a SingleCircularSlider. Check the README file.

**Comment by davidanaya** [comment]
Closing as this feature has already been implemented.
