### ISSUE TITLE
Click instead of dragging the slider

### ISSUE THREAD

**Issue by subhash279** [davidanaya/flutter-circular-slider#4]
Hi,
Great work on the sliders. Just a quick query, lets say there is only one handler, then instead of dragging, is it possible to click somewhere on the circle and the handler to move there. This is  similar to how linear slider in flutter would work. Thanks!

**Comment by davidanaya** [comment]
Hi @subhash279 I didn't have plans to put only one slider.
How would that work? Counting from the only one handler to ... where?
Once we figure this out I think I could implement this.

**Comment by davidanaya** [comment]
@subhash279 new version released, you can use now a SingleCircularSlider. Check the README file.

**Comment by subhash279** [comment]
Hi, Thanks a lot. I will check it out.

**Comment by davidanaya** [comment]
Closing as the feature has already been implemented.
