### ISSUE TITLE
Bug have to be fixed

### ISSUE THREAD

**Issue by YasserOJ** [davidanaya/flutter-circular-slider#6]
So simply the bug happen when the start is at 0 and stays in 0 and you drag the end to 0 the slider disappear

**Comment by YasserOJ** [comment]
![Untitled](https://user-images.githubusercontent.com/26030291/58634109-5dd57200-82e2-11e9-8c9a-0f7f34c7cfc2.gif)

**Comment by davidanaya** [comment]
Thanks @YasserOJ I'll look into it

**Comment by davidanaya** [comment]
Closing as the bug has been fixed.
