### ISSUE TITLE
What if I want one side drag ?

### ISSUE THREAD

**Issue by YasserOJ** [davidanaya/flutter-circular-slider#7]
I want that the drag happens from one side so always the init is 0 and you can't change it and only one circle to drag ?

**Comment by davidanaya** [comment]
I could think about this.
Let me have a look at it @YasserOJ

**Comment by davidanaya** [comment]
@YasserOJ new version released, you can use now a SingleCircularSlider. Check the README file.

**Comment by davidanaya** [comment]
Closing, the feature has already been implemented.

**Comment by Usmani7** [comment]
Hi, can we disable the drag?
